### ISSUE TITLE
Permission to make a 1 player vs AI feature

### ISSUE THREAD

**Issue by LuisRamosOfficial** [ShermanPI/tic-tac-toe#1]
Hey ShermanPi! Hope u doing well. I stumbled upon your Tic Tac Toe rep and it's quite cool.

So, I'm asking your permission to use your repository to train with machine learning and add a 1 player vs AI feature to your game.
Would it be cool if I forked your repository and gave it a shot? I just think this could be a fun twist, and I'd love to contribute if you're up for it.
Let me know what you think. Looking forward to your thoughts.

**Comment by ShermanPI** [comment]
Hi! The fact that the application can have this game mode seems great to me, I don't see any drawbacks in that you can fork the project. I hope the best and good luck🚀

**Comment by LuisRamosOfficial** [comment]
Hello again! Thank you for giving permission.
I kinda thought it would be much difficult but I probably over complicated the problem.
With a simple script using a score system made a computer player to play with the user.
if you want to check out the code, its here: https://github.com/LuisRamosOfficial/Tic-Tac-Toe-in-Javascript


Even added a simple menu to choose between the different modes
![image](https://github.com/ShermanPI/tic-tac-toe/assets/120321858/32485ceb-0960-44e5-8f86-619c968f7edb)


## Other Changes

* Moved the css files and used Modular Sass to stylize.
* added some dependencies, so if you want to test on your machine first you should run 
```
$ npm install
```
* Other minor changes

## Thank you
This is my first time contributing for another one's project so I am very grateful for giving me this opportunity!
Feel free to add my Idea to your project if you find to like it a lot. Looking forward for more collaborations between the both of us 🤝
